import React from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useSelector } from "react-redux";
import { RootState } from "@/store/store";
import { useNavigation, useRoute, RouteProp } from "@react-navigation/native";
import { RootStackParamList } from "@/src/types/navigation";
import type { StackNavigationProp } from "@react-navigation/stack";

type AIEvaluationReportRouteProp = RouteProp<
  RootStackParamList,
  "AIEvaluationReport"
>;
type Nav = StackNavigationProp<RootStackParamList, "AIEvaluationReport">;

// This will be the structure for AI evaluation data
interface AIEvaluationData {
  overallScore?: number;
  feedback?: string;
  strengths?: string[];
  improvements?: string[];
  detailedAnalysis?: string;
}

export default function AIEvaluationReportScreen() {
  const navigation = useNavigation<Nav>();
  const route = useRoute<AIEvaluationReportRouteProp>();
  const theme = useSelector((state: RootState) => state.theme.isLight);

  // For now, we'll use dummy data - this will be replaced with actual AI evaluation
  const dummyEvaluation: AIEvaluationData = {
    overallScore: 85,
    feedback:
      "Your answer demonstrates a good understanding of the topic with clear explanations and relevant examples.",
    strengths: [
      "Well-structured answer with clear introduction",
      "Good use of relevant examples",
      "Logical flow of ideas",
    ],
    improvements: [
      "Could include more statistical data to support arguments",
      "Conclusion could be more comprehensive",
      "Some points need deeper elaboration",
    ],
    detailedAnalysis:
      "The answer shows strong conceptual understanding. Your introduction effectively sets the context, and you've maintained coherence throughout. However, incorporating more data-driven insights would strengthen your arguments significantly.",
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return "#00C853";
    if (score >= 60) return "#FFA726";
    return "#FF5252";
  };

  return (
    <SafeAreaView
      style={[
        styles.container,
        { backgroundColor: theme ? "#222831" : "#F5F5F5" },
      ]}
    >
      {/* Header */}
      <View
        style={[
          styles.header,
          { backgroundColor: theme ? "#393E46" : "#FFFFFF" },
        ]}
      >
        <TouchableOpacity
          onPress={() => navigation.goBack()}
          style={styles.backButton}
        >
          <Text style={[styles.backButtonText, { color: "#00ADB5" }]}>
            ← Back
          </Text>
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: theme ? "#EEEEEE" : "#222831" }]}>
          AI Evaluation Report
        </Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
      >
        {/* AI Badge */}
        <View style={styles.aiBadgeContainer}>
          <View style={styles.aiBadge}>
            <Text style={styles.aiBadgeText}>AI</Text>
          </View>
          <Text style={[styles.aiBadgeLabel, { color: theme ? "#AAAAAA" : "#666666" }]}>
            Generated by Artificial Intelligence
          </Text>
        </View>

        {/* Overall Score Card */}
        <View
          style={[
            styles.card,
            { backgroundColor: theme ? "#393E46" : "#FFFFFF" },
          ]}
        >
          <Text style={[styles.cardTitle, { color: theme ? "#EEEEEE" : "#222831" }]}>
            Overall Score
          </Text>
          <View style={styles.scoreContainer}>
            <Text
              style={[
                styles.scoreText,
                { color: getScoreColor(dummyEvaluation.overallScore || 0) },
              ]}
            >
              {dummyEvaluation.overallScore}
            </Text>
            <Text style={[styles.scoreOutOf, { color: theme ? "#AAAAAA" : "#666666" }]}>
              / 100
            </Text>
          </View>
        </View>

        {/* Overall Feedback Card */}
        <View
          style={[
            styles.card,
            { backgroundColor: theme ? "#393E46" : "#FFFFFF" },
          ]}
        >
          <Text style={[styles.cardTitle, { color: theme ? "#EEEEEE" : "#222831" }]}>
            Overall Feedback
          </Text>
          <Text style={[styles.feedbackText, { color: theme ? "#CCCCCC" : "#444444" }]}>
            {dummyEvaluation.feedback}
          </Text>
        </View>

        {/* Strengths Card */}
        <View
          style={[
            styles.card,
            { backgroundColor: theme ? "#393E46" : "#FFFFFF" },
          ]}
        >
          <Text style={[styles.cardTitle, { color: theme ? "#EEEEEE" : "#222831" }]}>
            Strengths ✓
          </Text>
          {dummyEvaluation.strengths?.map((strength, index) => (
            <View key={index} style={styles.listItem}>
              <View style={[styles.bulletPoint, { backgroundColor: "#00C853" }]} />
              <Text style={[styles.listItemText, { color: theme ? "#CCCCCC" : "#444444" }]}>
                {strength}
              </Text>
            </View>
          ))}
        </View>

        {/* Areas for Improvement Card */}
        <View
          style={[
            styles.card,
            { backgroundColor: theme ? "#393E46" : "#FFFFFF" },
          ]}
        >
          <Text style={[styles.cardTitle, { color: theme ? "#EEEEEE" : "#222831" }]}>
            Areas for Improvement
          </Text>
          {dummyEvaluation.improvements?.map((improvement, index) => (
            <View key={index} style={styles.listItem}>
              <View style={[styles.bulletPoint, { backgroundColor: "#FFA726" }]} />
              <Text style={[styles.listItemText, { color: theme ? "#CCCCCC" : "#444444" }]}>
                {improvement}
              </Text>
            </View>
          ))}
        </View>

        {/* Detailed Analysis Card */}
        <View
          style={[
            styles.card,
            { backgroundColor: theme ? "#393E46" : "#FFFFFF" },
          ]}
        >
          <Text style={[styles.cardTitle, { color: theme ? "#EEEEEE" : "#222831" }]}>
            Detailed Analysis
          </Text>
          <Text style={[styles.feedbackText, { color: theme ? "#CCCCCC" : "#444444" }]}>
            {dummyEvaluation.detailedAnalysis}
          </Text>
        </View>

        {/* Disclaimer */}
        <View style={styles.disclaimerContainer}>
          <Text style={[styles.disclaimerText, { color: theme ? "#888888" : "#999999" }]}>
            This evaluation is generated by AI and should be used as a guide.
            Always verify with official sources and human expertise.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  backButton: {
    paddingVertical: 8,
    paddingRight: 16,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: "600",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
  },
  placeholder: {
    width: 60,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  aiBadgeContainer: {
    alignItems: "center",
    marginBottom: 24,
  },
  aiBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(0, 173, 181, 0.15)",
    borderWidth: 2,
    borderColor: "#00ADB5",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  aiBadgeText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#00ADB5",
  },
  aiBadgeLabel: {
    fontSize: 12,
    fontWeight: "500",
    fontStyle: "italic",
  },
  card: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 16,
  },
  scoreContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    marginVertical: 12,
  },
  scoreText: {
    fontSize: 64,
    fontWeight: "700",
  },
  scoreOutOf: {
    fontSize: 24,
    fontWeight: "600",
    marginLeft: 4,
  },
  feedbackText: {
    fontSize: 15,
    lineHeight: 24,
    fontWeight: "400",
  },
  listItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  bulletPoint: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginTop: 6,
    marginRight: 12,
  },
  listItemText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "400",
  },
  disclaimerContainer: {
    marginTop: 8,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  disclaimerText: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    fontStyle: "italic",
  },
});
