import React, { useEffect, useState } from "react";
import { View, StyleSheet, ScrollView } from "react-native";
import { useSelector } from "react-redux";
import { RootState } from "@/store/store";
import { useRoute, RouteProp, useNavigation } from "@react-navigation/native";
import { RootStackParamList } from "@/src/types/navigation";
import { StackNavigationProp } from "@react-navigation/stack";
import { supabase } from "@/src/supabaseConfig";
import DisclaimerText from "@/src/components/atoms/DisclaimerText";
import OverallScoreCard from "../components/OverallScoreCard";
import OverallFeedbackCard from "../components/OverallFeedbackCard";
import StrengthsCard from "../components/StrengthsCard";
import ImprovementsCard from "../components/ImprovementsCard";
import DetailedAnalysisCard from "../components/DetailedAnalysisCard";
import AIEvaluationErrorCard from "../components/AIEvaluationErrorCard";
import AIEvaluationLoader from "../components/AIEvaluationLoader";
import Subtitle from "@/src/components/atoms/Subtitle";
import FooterText from "@/src/components/atoms/FooterText";
import useAIEvaluationReport from "../hooks/useAIEvaluationReport";

type Nav = StackNavigationProp<RootStackParamList>;

type AIEvaluationReportRouteProp = RouteProp<
  RootStackParamList,
  "AIEvaluationReport"
>;

interface AIEvaluationReportData {
  // Scores
  relevance_score: number;
  structure_score: number;
  content_depth_score: number;
  presentation_score: number;
  innovation_score: number;
  total_score: number;

  // Feedback text
  summary: string;
  detailed_feedback: string;
  strengths: string[];
  improvements: string[];
}

interface AIEvaluationError {
  type: "validation" | "technical";
  message: string;
}

export default function AIEvaluationReportScreen() {
  const route = useRoute<AIEvaluationReportRouteProp>();
  const navigation = useNavigation<Nav>();
  const isLight = useSelector((s: RootState) => s.theme.isLight);
  const { postId } = route.params;

  // State for post data
  const [post, setPost] = useState<{
    images: string[];
    question: string | null;
  } | null>(null);
  const [fetchingPost, setFetchingPost] = useState(true);

  // Fetch post data
  useEffect(() => {
    const fetchPost = async () => {
      try {
        const { data, error } = await supabase
          .from("posts")
          .select("images, question")
          .eq("id", postId)
          .single();

        if (error || !data) {
          console.error("Error fetching post:", error);
          setPost(null);
        } else {
          setPost(data);
        }
      } catch (err) {
        console.error("Error fetching post:", err);
        setPost(null);
      } finally {
        setFetchingPost(false);
      }
    };

    fetchPost();
  }, [postId]);

  // Use AI Evaluation hook
  const {
    evaluationReport,
    loading,
    error,
    refetch,
  } = useAIEvaluationReport(
    postId,
    post?.images || [],
    post?.question || null
  );

  // Trigger evaluation generation on mount (after post is fetched)
  useEffect(() => {
    if (!fetchingPost && post) {
      refetch();
    }
  }, [fetchingPost, post]);

  return (
    <View
      style={[
        styles.container,
        { backgroundColor: !isLight ? "#F0F0F0" : "#222831" },
      ]}
    >
      <AIEvaluationLoader visible={fetchingPost || loading} />
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
      >

        {/* Error State */}
        {!fetchingPost && !loading && error && (
          <AIEvaluationErrorCard
            errorType={error.type}
            errorMessage={error.message}
            onGoBack={() => navigation.goBack()}
          />
        )}

        {/* Success State - Show evaluation cards */}
        {!fetchingPost && !loading && !error && evaluationReport && (
          <>
            {/* Overall Score Card */}
            <OverallScoreCard data={evaluationReport} />

            {/* Overall Feedback Card */}
            <OverallFeedbackCard summary={evaluationReport.summary} />

            {/* Strengths Card */}
            <StrengthsCard strengths={evaluationReport.strengths} />

            {/* Areas for Improvement Card */}
            <ImprovementsCard improvements={evaluationReport.improvements} />

            {/* Detailed Analysis Card */}
            <DetailedAnalysisCard
              analysis={evaluationReport.detailed_feedback}
            />

            {/* Disclaimer */}
            <View style={styles.disclaimerContainer}>
              <FooterText text="This evaluation is generated by AI and should be used as a guide. Always verify with official sources and human expertise." />
            </View>
          </>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  disclaimerContainer: {
    marginBottom: 16,
    paddingHorizontal: 16,
  },
});
